### ISSUE TITLE
Verify the flatpak on Flathub

### ISSUE THREAD

**Issue by fice-t** [flathub/org.cockpit_project.CockpitClient#24]
A couple of months ago Flathub stable added the ability to verify applications. From [the documentation](https://docs.flathub.org/docs/for-users/verification):

> A verified app is an app that is published on Flathub by its original developer or a third party approved by the developer. Flathub has verified the developer's identity using the app id and the developer's website or profile on a source code hosting site.

https://flathub.org/about mentions the beginning step to getting an application verified.

**Comment by allisonkarlitskaya** [comment]
I've attempted (and failed) to perform verification via source repository control.  I asked for help on Matrix.  Hopefully we can do this easily enough.

**Comment by allisonkarlitskaya** [comment]
After some help with the flathub admins I've discovered the reason.  It's down to the fact that our app-id doesn't point directly to our GitHub organization (via `io.github.` or similar).

I've opened https://github.com/flathub/website/issues/1614, which would help us a lot.

Meanwhile, we can proceed with the web-based authentication mechanism.

**Comment by allisonkarlitskaya** [comment]
![image](https://github.com/flathub/org.cockpit_project.CockpitClient/assets/36541154/9ce80fe5-4ee4-4e9b-9f4d-6d0a816e4a3e)

Done.  Thanks for the suggestion!
