### ISSUE TITLE
Bump up to GNOME 47

### ISSUE THREAD

**Issue by garrett** [flathub/org.cockpit_project.CockpitClient#46]
GNOME 47 was just released, and Cockpit Client is using 45 still, which will become deprecated soon.

https://release.gnome.org/47/

Additionally, there are huge performance improvements (and a bunch of nice new features) for WebKitGTK, so Cockpit Client will directly benefit from the upgrade as well. (It's more than just a maintenance bump.)

**Comment by allisonkarlitskaya** [comment]
These issues belong upstream...
